### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by tambry** [TotempaaltJ/unix.click#1]
The website lacks IPv6 support and is inaccessible for people like me, who sometimes are on networks with no IPv4 support.

**Comment by martijnarts** [comment]
It's hosted on Netlify. I'll see what they can do regarding IPv6 :)

**Comment by martijnarts** [comment]
Got this response:

> We currently don't support AAAA records. If you DNS provider support CNAME flattening, ANAME or ALIAS records, you will want to use one of those records. Otherwise, you'll need to use an A record. Hope that answers your question.

I think Cloudflare supports CNAME flattening, so I'll try that and see if it works :)

**Comment by martijnarts** [comment]
I've updated the DNS record, and I'll retest the IPv6 availability when it's propagated.

**Comment by tambry** [comment]
I don't see the AAAA record having been set ([neither does Google](https://dns.google.com/query?name=unix.click&type=AAAA&dnssec=true)). I think the message from Netlify was recommending CNAME flattening for the problem described [here](https://www.netlify.com/blog/2016/01/12/this-weekends-ddos-attack-and-whats-in-a-cname). Seems like Netlify indeed has zero IPv6 support, which is very bad. Besides changing hosts, the only option is to probably throw the site behind something like a Cloudflare proxy.

**Comment by martijnarts** [comment]
I've changed this so that the domain is behind a Cloudflare proxy for now, which handles IPv6 traffic. It's not my preferred solution, but until Netlify supports IPv6 themselves this will have to do.

**Comment by tambry** [comment]
@TotempaaltJ That'll do. FYI, Netlify is supposedly getting IPv6 support by the end of the year. Thanks once again!
