### ISSUE TITLE
Add option for (JavaScript) milliseconds in timestamp

### ISSUE THREAD

**Issue by qJake** [TotempaaltJ/unix.click#6]
Adding an option for milliseconds when selecting or typing a date would allow JavaScript date formats to work. JavaScript uses UNIX timestamps + 3 additional decimal places of milliseconds.

For example, `unix.click` displays `1528617600` which in Javascript is `Sun Jan 18 1970`, but adding three 0's to the end (`1528617600000`) yields the correct date (`Sun Jun 10 2018`).

![js error](https://i.imgur.com/Z2e3aYB.png)

**Comment by martijnarts** [comment]
Hey, thanks for the issue report! I'm gonna track this feature in issue #4, so if you want to stay updated please subscribe to that!
